### PR TITLE
Update messages to be consistent with other SDMs

### PR DESCRIPTION
**Pull request by cdupuis**

### CODE REVIEW

**Comment by nebhale** [comment]
Pull request rebase is in progress because @slimslenderslacks pushed 2 commits to **master**:
- 9ee207d _update to send fingerprints in batches for large s..._
- d10761e _Merge branch 'master' of github.com:atomist/sdm-pa..._

**Comment by nebhale** [comment]
Pull request rebase is in progress because @slimslenderslacks pushed 2 commits to **master**:
- a9c3c49 _Autofix: TypeScript imports_
- af861d0 _Autofix: Third party licenses_

**Comment by fdserr** [comment]
Pull request rebase is in progress because @slimslenderslacks pushed 1 commit to **master**:
- 95aad13 _Repair docker test_

**Comment by jwaldrip** [comment]
Pull request rebase is in progress because @slimslenderslacks pushed 5 commits to **master**:
- cf18f09 _Autofix: TypeScript header_
- 836a2c8 _Autofix: tslint_
- c20ad57 _Autofix: TypeScript imports_
- f0444d3 _Autofix: NPM package lock_
- 672bb49 _Autofix: Third party licenses_

**Comment by bconneen** [comment]
Pull request rebase is in progress because @slimslenderslacks pushed 1 commit to **master**:
- 6baa0fb _actually fix_

**Comment by bconneen** [comment]
Pull request rebase is in progress because @atomist-bot pushed 1 commit to **master**:
- 0f9f913 _Version: increment after 3.0.8 release_

**Comment by fdserr** [comment]
Pull request rebase is in progress because @atomist-bot pushed 1 commit to **master**:
- 0290042 _Changelog: add release 3.0.8_

**Comment by cdupuis** [comment]
Pull request rebase is in progress because @cdupuis pushed 1 commit to **master**:
- 15bc818 _Update all dependencies_

**Comment by cdupuis** [comment]
Pull request rebase is in progress because @cdupuis pushed 2 commits to **master**:
- 46150b3 _Autofix: NPM package lock_
- 55b61c2 _Autofix: Third party licenses_

**Comment by cdupuis** [comment]
Pull request rebase is in progress because @slimslenderslacks pushed 1 commit to **master**:
- 0501155 _PR workflows with with type/name are working_

**Comment by cdupuis** [comment]
Pull request rebase is in progress because @slimslenderslacks pushed 1 commit to **master**:
- e771acf _Autofix: tslint_

**Pull request merged**
